services:

  # https://medium.com/workleap/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need-2f0b74dd8384

  mongosh:
    image: docker.io/mongodb/mongodb-community-server:latest
    entrypoint: mongosh mongodb://mongodb1:27017/?ssl=false -f /config/functions.js
    command:    -f /config/functions.js --shell 
    volumes: 
      - ./config:/config:ro
    deploy:
      replicas: 0

  mongostat:
    image: docker.io/mongodb/mongodb-community-server:latest
    command: bash -c 'mongostat mongodb://mongodb1:27017/?ssl=false -o "$$(paste -sd, /config/mongostat.fields)"'
    volumes: 
      - ./config:/config:ro
    deploy:
      replicas: 0

  mongodb1:
    image: docker.io/mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017

  mongodb_exporter:
    image: percona/mongodb_exporter:0.43.1
    command: --mongodb.uri=mongodb://mongodb1:27017/?ssl=false --collect-all
    ports:
     - 9216:9216
    depends_on:
      - mongodb1
  
  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
      #- "host.docker.internal:172.17.0.1"
    image: prom/prometheus:v2.37.9
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    user: "0:0"
    volumes:
      - ./config:/etc/prometheus:ro
    restart: unless-stopped
    depends_on:
      - mongodb_exporter

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    user: "0:0"
    volumes:
      - ./config:/etc/grafanax:ro
      - ./config:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  pmm-data:
    image: percona/pmm-server:latest
    entrypoint: /bin/true
    volumes:
      - /var/tmp/pmm/prometheus/data:/opt/prometheus/data
      - /var/tmp/pmm/consul-data:/opt/consul-data
      - /var/tmp/pmm/mysql:/var/lib/mysql
      - /var/tmp/pmm/grafana:/var/lib/grafana

  pmm-server:
    image: percona/pmm-server:latest
    container_name: pmm-server
    ports:
      - '7000:80'
    restart: always
    environment:
      - SERVER_USER=admin
      - SERVER_PASSWORD=admin
      - METRICS_RETENTION=10h
      - METRICS_MEMORY=4194304
      - METRICS_RESOLUTION=1s
      - QUERIES_RETENTION=30
    volumes_from:
      - pmm-data
